Try to download artifact from other commit in workflow

diff --git a/.github/workflows/CI_test_suite.yml b/.github/workflows/CI_test_suite.yml
--- a/.github/workflows/CI_test_suite.yml
+++ b/.github/workflows/CI_test_suite.yml
@@ -10,44 +10,44 @@ on:
 
 jobs:
 
-  SystemTests:
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
+  # SystemTests:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - uses: actions/checkout@v4
 
-    - name: Set up Go
-      uses: actions/setup-go@v5
-      with:
-        go-version-file: go.mod
+  #   - name: Set up Go
+  #     uses: actions/setup-go@v5
+  #     with:
+  #       go-version-file: go.mod
 
-    - name: Set up Python
-      uses: actions/setup-python@v5
-      with:
-        python-version: '3.12'
+  #   - name: Set up Python
+  #     uses: actions/setup-python@v5
+  #     with:
+  #       python-version: '3.12'
 
-    - name: System tests dependencies
-      run: xargs -a system_test_requirements.txt sudo apt-get install
-      working-directory: test_suite
+  #   - name: System tests dependencies
+  #     run: xargs -a system_test_requirements.txt sudo apt-get install
+  #     working-directory: test_suite
 
-    - name: Performance tests dependencies
-      run: pip install -r python_requirements.txt
-      working-directory: test_suite
+  #   - name: Performance tests dependencies
+  #     run: pip install -r python_requirements.txt
+  #     working-directory: test_suite
 
-    - name: Run system tests
-      id: system-test
-      run: ./system_tests.sh -c 0
-      working-directory: test_suite
-      continue-on-error: true
+  #   - name: Run system tests
+  #     id: system-test
+  #     run: ./system_tests.sh -c 0
+  #     working-directory: test_suite
+  #     continue-on-error: true
 
-    - name: Upload system test logs
-      uses: actions/upload-artifact@v4
-      with:
-        name: system-test-logs
-        path: test_suite/system_test_logs/
+  #   - name: Upload system test logs
+  #     uses: actions/upload-artifact@v4
+  #     with:
+  #       name: system-test-logs
+  #       path: test_suite/system_test_logs/
 
-    - name: Fail job if system test failed (for clarity in GitHub UI)
-      if: ${{ steps.system-test.outcome == 'failure' }}
-      run: exit 1
+  #   - name: Fail job if system test failed (for clarity in GitHub UI)
+  #     if: ${{ steps.system-test.outcome == 'failure' }}
+  #     run: exit 1
 
   PerformanceTests:
     runs-on: ubuntu-latest
@@ -87,7 +87,7 @@ jobs:
     - name: Upload performance test data
       uses: actions/upload-artifact@v4
       with:
-        name: performance-test-data-${{ github.sha }}
+        name: performance-test-data
         path: test_suite/system_test_logs/performance/*/performance_test_*_data.json
 
     - name: Upload full performance test logs
@@ -100,29 +100,38 @@ jobs:
       if: ${{ steps.system-test.outcome == 'failure' }}
       run: exit 1
 
-  IntegrationTests:
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
+    - name: Download artifact from previous commit
+      uses: dawidd6/action-download-artifact@v9
+      with: 
+        commit: d714530587846aa184cec41049b90ec3c023cd11
+        name: performance-test-data-d714530587846aa184cec41049b90ec3c023cd11
 
-    - name: Set up Go
-      uses: actions/setup-go@v5
-      with:
-        go-version-file: go.mod
+    - name: Check if artifact was successfully downloaded
+      run: ls
 
-    - name: Run integration tests
-      id: integration-test
-      run: go test -coverpkg=./... -coverprofile cover.out -v ./...
+  # IntegrationTests:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - uses: actions/checkout@v4
 
-    - name: Create integration test coverage report
-      run: go tool cover -html cover.out -o cover.html
+  #   - name: Set up Go
+  #     uses: actions/setup-go@v5
+  #     with:
+  #       go-version-file: go.mod
 
-    - name: Upload integration test coverage report
-      uses: actions/upload-artifact@v4
-      with:
-        name: integration-test-coverage
-        path: cover.html
+  #   - name: Run integration tests
+  #     id: integration-test
+  #     run: go test -coverpkg=./... -coverprofile cover.out -v ./...
 
-    - name: Fail job if integration test failed (for clarity in GitHub UI)
-      if: ${{ steps.integration-test.outcome == 'failure' }}
-      run: exit 1
+  #   - name: Create integration test coverage report
+  #     run: go tool cover -html cover.out -o cover.html
+
+  #   - name: Upload integration test coverage report
+  #     uses: actions/upload-artifact@v4
+  #     with:
+  #       name: integration-test-coverage
+  #       path: cover.html
+
+  #   - name: Fail job if integration test failed (for clarity in GitHub UI)
+  #     if: ${{ steps.integration-test.outcome == 'failure' }}
+  #     run: exit 1
